apiVersion: kmambo.io/v1alpha1
kind: Workflow
metadata:
  name: iot-data-ingestion-task
  labels:
    app.kubernetes.io/name: workflow
    app.kubernetes.io/instance: workflow-sample
    app.kubernetes.io/part-of: crd-maker
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: crd-maker
spec:
  tasks:
    - name: iot-data-ingestion-task
      namespace: iot-workflow-ns
      events:
        src:
          type: service
          name: iot-http-push
          init: true
        dst:
          type: queue
          name: iot-pubsub
    - name: iot-data-pii-filter-task
      namespace: iot-workflow-ns
      events:
        src:
          type: queue
          name: iot-pubsub
        dst:
          type: database
          name: iot-datalake
          final: true