@startuml
'https://plantuml.com/component-diagram



node "Other Groups" {
    () HTTP
    package "Task 1" {
      cloud "Task 1 Service" as T1

      T1 -> [Task One - Pod 1]
      T1 -> [Task One - Pod 2]
      T1 -> [...]
      T1 -> [Task One - Pod //N//]
    }

    database "Redis" {
    }

"Task 1" -> Redis
  FTP - [Second Component]
  [First Component] --> FTP
}





[Another Component] --> [Example 1]
[Example 1] --> [Folder 3]
[Folder 3] --> [Frame 4]

@enduml